name: "Generate PDF from TeX"
on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: .
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TeX to PDF
        uses: ./actions/build-resume
        env:
          OUT_DIR: public
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: public/
      - name: Set Release Tag
        run: echo "::set-env name=TIMESTAMP::$(date +'%Y%m%d-%H%M%S')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TIMESTAMP }}
          release_name: Release ${{ env.TIMESTAMP }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf

