name: "Generate PDF from TeX"
on:
  push:
    branches: [main]
    paths:
      - 'resume.tex'
      - 'resume.cls'
defaults:
  run:
    working-directory: .
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TeX to PDF
        uses: ./actions/build-resume
        env:
          OUT_DIR: public
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: public/
      - name: Set Release Tag
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d-%H%M%S')"
      - name: Create Release
        id: create_release
        uses: nicolalamacchia/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.timestamp.outputs.timestamp }}
          release_name: Release ${{ steps.timestamp.outputs.timestamp }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: nicolalamacchia/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
      - name: Notify
        run: |
          curl --fail -X POST \
            --data-urlencode "token=${{ secrets.RELEASE_TOKEN }}" \
            --data-urlencode "app=resume" \
            --data-urlencode "ts=${{ steps.timestamp.outputs.timestamp }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            https://nicola.link/ci-update

